### ISSUE TITLE
Would you like to maintain snaplet-fay?

### ISSUE THREAD

**Issue by bergmark** [faylang/snaplet-fay#13]
I've decided to stop maintaining this package since fay development and to a larger degree this package doesn't any much attention.

If you'd like to take it over please let me know your hackage user name and i'll transfer it to you, no strings attached.

**Comment by swamp-agr** [comment]
@bergmark I think it might be closed, since started from couple days ago I became maintainer. 😄 
I am currently assessing everything here and planning time I should spent on fay's related activities.
